export interface MonitorOrg {
  name: string
  sector: 'academia' | 'industry' | 'international' | 'india'
  country: string
  careersUrl?: string
  rssUrl?: string
  apiType: 'rss' | 'usajobs' | 'websearch' | 'adzuna' | 'natureJobs'
  searchQuery: string
  slowFetch?: boolean  // Add extra inter-scan delay to respect org rate limits
}

// Academic acronyms that map to Indian government research institutes
const GOVT_RESEARCH_ACRONYMS = /\b(CSIR|TIFR|IISc|NCBS|IGIB)\b/

/**
 * Returns a display subsector for an org:
 *  - Indian government research institutes → 'Govt Research'
 *  - Known pharma/biotech pattern → 'Industry'
 *  - Everything else falls through to the org's sector label
 */
export function getOrgSubsector(org: MonitorOrg): string {
  if (GOVT_RESEARCH_ACRONYMS.test(org.name)) return 'Govt Research'
  if (org.sector === 'industry') return 'Industry'
  if (org.sector === 'india') return 'India Academia'
  if (org.sector === 'international') return 'International'
  return 'Academia'
}

// ─── webSearch is ONLY used for orgs with no free source ─────────────────────
// Max 15 websearch orgs. All others use RSS or USAJobs (free, no AI cost).
// Cost: ~60 webSearch calls/month @ ~$0.03/call = ~$1-2/month for monitor

export const MONITOR_ORGS: MonitorOrg[] = [
  // ═══ ACADEMIA — US Government (USAJobs — free, no AI cost) ═══
  { name: "NIH NHLBI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "cardiovascular postdoc researcher NHLBI" },
  { name: "NIH NIGMS", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "postdoctoral researcher molecular biology NIGMS" },
  { name: "NIH NCI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cancer biology NCI" },
  { name: "FDA", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist molecular biology FDA" },
  { name: "CDC", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cardiovascular molecular biology CDC" },

  // ═══ ACADEMIA — RSS feeds (free, no AI cost) ═══
  // RSS feeds — only sources that emit individual per-job items (not search-page aggregators)
  { name: "Cold Spring Harbor Laboratory", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://cshl.edu/careers/feed/",
    searchQuery: "Cold Spring Harbor postdoc molecular biology genomics" },
  { name: "EMBL Jobs", sector: "international", country: "Germany",
    apiType: "rss",
    rssUrl: "https://www.embl.org/jobs/rss/",
    searchQuery: "EMBL postdoctoral fellowship cardiovascular molecular biology" },
  { name: "Wellcome Sanger Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.sanger.ac.uk/careers/rss/",
    searchQuery: "Wellcome Sanger postdoctoral researcher genomics cardiovascular" },
  { name: "Francis Crick Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.crick.ac.uk/careers/vacancies/rss",
    searchQuery: "Francis Crick postdoc cardiovascular molecular biology" },
  // Jobs.ac.uk — filtered RSS returns individual UK academic job postings
  { name: "Jobs.ac.uk", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.jobs.ac.uk/search/?rss=1&keywords=cardiovascular+molecular+biology+postdoc+research+scientist",
    searchQuery: "cardiovascular postdoc molecular biology UK" },
  // Nature Jobs websearch — Gemini finds specific individual listings
  { name: "Nature Jobs", sector: "academia", country: "Global",
    apiType: "websearch",
    searchQuery: "site:nature.com/naturecareers postdoc cardiovascular molecular biology research scientist 2026" },
  // Science Careers websearch — Gemini finds specific individual listings
  { name: "Science Careers", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:jobs.sciencecareers.org postdoc cardiovascular molecular biology research scientist 2026" },

  // ═══ ACADEMIA — webSearch (no free source — keep to 15 total) ═══
  { name: "Harvard Medical School", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Harvard Medical School postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://academicpositions.harvard.edu" },
  { name: "Stanford Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Stanford Medicine postdoctoral researcher cardiovascular 2026",
    careersUrl: "https://med.stanford.edu/careers" },
  { name: "Mayo Clinic Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Mayo Clinic postdoc research scientist cardiovascular 2026",
    careersUrl: "https://jobs.mayoclinic.org" },
  { name: "Broad Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Broad Institute postdoctoral associate genomics molecular biology 2026",
    careersUrl: "https://www.broadinstitute.org/careers" },
  { name: "MIT Biology", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "MIT postdoctoral researcher molecular biology cardiovascular 2026" },
  { name: "UCSF", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UCSF postdoc cardiovascular cell biology molecular biology 2026",
    careersUrl: "https://jobs.ucsf.edu" },
  { name: "Johns Hopkins Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Johns Hopkins postdoctoral researcher cardiovascular 2026",
    careersUrl: "https://jobs.jhu.edu" },
  { name: "Salk Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Salk Institute postdoc cardiovascular cell biology 2026",
    careersUrl: "https://www.salk.edu/careers" },
  { name: "Columbia University Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Columbia University postdoc cardiovascular research 2026" },
  { name: "Yale School of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Yale Medicine postdoctoral researcher cardiovascular 2026" },
  { name: "Gladstone Institutes", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Gladstone Institutes postdoc cardiovascular genomics 2026",
    careersUrl: "https://gladstone.org/careers" },
  { name: "Scripps Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Scripps Research postdoctoral scientist cardiovascular 2026" },
  { name: "UT Southwestern Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UT Southwestern postdoc cardiovascular research 2026" },
  { name: "Baylor College of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Baylor College Medicine postdoc cardiovascular 2026" },
  { name: "Washington University St Louis", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "WashU postdoctoral researcher cardiovascular molecular biology 2026" },
  { name: "Weill Cornell Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Weill Cornell postdoc cardiovascular research scientist 2026" },

  // ═══ INDUSTRY — webSearch (no free API for these orgs) ═══
  // ── Industry search queries are Pooja-profile-specific ──────────────────────
  // Her CV highlights: cardiovascular, transgenic mouse models, Cre-lox,
  // RNA-seq, cellular senescence, echocardiography, Langendorff, IHC, confocal
  // Target: Research Scientist, Senior Scientist, Principal Scientist, Scientist I/II/III
  // She published co-first author in Nature Communications (IF 15.7)

  { name: "Genentech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Genentech Research Scientist Senior Scientist cardiovascular molecular biology RNA-seq transgenic mouse 2026",
    careersUrl: "https://www.gene.com/careers" },
  { name: "AstraZeneca US", sector: "industry", country: "USA",
    apiType: "websearch", slowFetch: true,
    searchQuery: "AstraZeneca Scientist Senior Scientist cardiovascular heart failure cardiomyopathy molecular biology 2026",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "Novartis US", sector: "industry", country: "USA",
    apiType: "websearch", slowFetch: true,
    searchQuery: "Novartis Research Scientist Senior Scientist cardiovascular heart disease molecular biology mouse model 2026",
    careersUrl: "https://careers.novartis.com" },
  { name: "Pfizer Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Pfizer Scientist Senior Scientist cardiovascular molecular biology cardiac mouse model RNA-seq 2026",
    careersUrl: "https://www.pfizer.com/careers" },
  { name: "Amgen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Amgen Scientist Senior Scientist cardiovascular molecular biology cardiomyocyte mouse model 2026",
    careersUrl: "https://careers.amgen.com" },
  { name: "Bristol Myers Squibb", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "BMS Bristol Myers Squibb Scientist cardiovascular molecular genetics RNA-seq mouse model 2026",
    careersUrl: "https://careers.bms.com" },
  { name: "Regeneron", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Regeneron Scientist Senior Scientist cardiovascular molecular biology in-vivo mouse 2026",
    careersUrl: "https://careers.regeneron.com" },
  { name: "Moderna", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Moderna Scientist Senior Scientist cardiovascular molecular biology mRNA cardiac 2026",
    careersUrl: "https://www.modernatx.com/careers" },
  { name: "Eli Lilly", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Eli Lilly Scientist Senior Scientist cardiovascular cardiac molecular biology mouse model 2026",
    careersUrl: "https://careers.lilly.com" },
  { name: "Merck Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Merck MSD Scientist Senior Scientist cardiovascular molecular biology cardiac RNA-seq 2026",
    careersUrl: "https://jobs.merck.com" },
  { name: "Alnylam Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Alnylam Scientist Senior Scientist cardiovascular RNA therapeutics cardiomyopathy mouse model 2026",
    careersUrl: "https://www.alnylam.com/careers" },
  { name: "Sanofi Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Sanofi Scientist Senior Scientist cardiovascular molecular biology heart failure mouse 2026" },
  { name: "Janssen Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Janssen J&J Scientist Senior Scientist cardiovascular molecular biology cardiac mouse model 2026" },
  { name: "Biogen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Biogen Scientist Senior Scientist molecular biology RNA-seq mouse model senescence 2026" },
  { name: "Vertex Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Vertex Pharmaceuticals Scientist Senior Scientist molecular biology genomics RNA-seq 2026" },
  { name: "10x Genomics", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "10x Genomics Scientist Senior Scientist spatial transcriptomics single-cell RNA-seq biology 2026" },
  { name: "Recursion Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Recursion Pharmaceuticals Scientist Senior Scientist cell biology mouse model in-vivo 2026" },
  { name: "BioNTech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "BioNTech Scientist Senior Scientist molecular biology cardiovascular mRNA mouse model 2026" },

  // ═══ INTERNATIONAL — RSS feeds (free, no AI cost) ═══
  { name: "MRC LMS London", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC London Institute Medical Sciences postdoc cardiovascular 2026" },
  { name: "Max Planck Heart and Lung", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Max Planck Institute Heart Lung postdoc cardiovascular 2026" },
  { name: "Karolinska Institute", sector: "international", country: "Sweden",
    apiType: "websearch",
    searchQuery: "Karolinska Institute postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://ki.se/en/vacancies" },
  { name: "ETH Zurich", sector: "international", country: "Switzerland",
    apiType: "websearch",
    searchQuery: "ETH Zurich postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://jobs.ethz.ch" },
  { name: "University of Toronto", sector: "international", country: "Canada",
    apiType: "websearch",
    searchQuery: "University of Toronto postdoc cardiovascular molecular biology 2026" },
  { name: "A*STAR Singapore", sector: "international", country: "Singapore",
    apiType: "websearch",
    searchQuery: "ASTAR Singapore postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://www.a-star.edu.sg/careers" },
  { name: "Peter MacCallum Cancer Centre", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "Peter MacCallum postdoc molecular biology genomics 2026" },

  // ═══ INDIA — webSearch (no free API available for Indian institutes) ═══
  { name: "NCBS Bangalore", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "NCBS Bangalore research scientist faculty cardiovascular molecular biology 2026",
    careersUrl: "https://www.ncbs.res.in/jobs" },
  // ── India search queries: Pooja-specific — PhD Molecular Genetics (Delhi), ─
  // ── Postdoc cardiovascular/heme/senescence, Nature Comms co-first author    ─
  // ── Target: Assistant Professor, Scientist C/D/E, Staff Scientist, ≥₹22 LPA ─

  // ═══ INDIA — Govt Research Institutes (DBT/CSIR/ICMR) ═══
  { name: "TIFR Mumbai", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "TIFR Mumbai faculty scientist assistant professor molecular genetics cardiovascular biology 2026" },
  { name: "IISc Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IISc Bangalore faculty assistant professor molecular biology cardiovascular genetics mouse model 2026" },
  { name: "IGIB Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IGIB Delhi Scientist C D E cardiovascular genomics molecular genetics RNA-seq 2026" },
  { name: "CCMB Hyderabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "CCMB Hyderabad Scientist C D E faculty molecular biology cardiovascular cell biology 2026" },
  { name: "inStem Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "inStem Bangalore faculty investigator cardiovascular stem cell biology molecular genetics 2026" },
  { name: "NII Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "NII Delhi Scientist C D faculty molecular biology cardiovascular immunology 2026" },
  { name: "JNCASR Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "JNCASR Bangalore faculty associate professor molecular biology cardiovascular genomics 2026" },
  { name: "IISER Pune", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Pune faculty assistant professor biology cardiovascular molecular genetics 2026" },
  { name: "RCB Faridabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "RCB Regional Centre Biotechnology Faridabad faculty scientist cardiovascular molecular biology 2026" },
  { name: "DBT-THSTI Faridabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "THSTI Faridabad scientist faculty cardiovascular translational medicine molecular biology 2026" },
  { name: "RGCB Trivandrum", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "RGCB Trivandrum Scientist C D cardiovascular molecular biology genetics 2026" },
  { name: "NIMHANS Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "NIMHANS Bangalore scientist faculty molecular biology neuroscience cardiovascular 2026" },
  { name: "CSIR-CDRI Lucknow", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "CSIR CDRI Lucknow Scientist C D cardiovascular molecular biology mouse model 2026" },
  { name: "CSIR-IICB Kolkata", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "CSIR IICB Kolkata Scientist C D cardiovascular molecular biology cell biology 2026" },

  // ═══ INDIA — Key Indian Govt Fellowships Pooja is Eligible For ═══
  // These are re-entry fellowships for Indian scientists returning from abroad
  { name: "DBT Ramalingaswami Fellowship", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "DBT Ramalingaswami Re-entry Fellowship 2026 cardiovascular molecular biology application open" },
  { name: "DST-SERB National Science Chair", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "DST SERB Early Career Research Award ECR 2026 biology cardiovascular molecular genetics" },
  { name: "DBT Wellcome Trust India Alliance", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "DBT Wellcome Trust India Alliance Fellowship 2026 cardiovascular biology molecular genetics open call" },
  { name: "ICMR Extramural Research Grant", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "ICMR Extramural Research scientist position cardiovascular heart disease molecular biology 2026" },

  // ═══ INDIA — Industry (Pharma/Biotech) ═══
  { name: "Biocon Biologics", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Biocon Biologics Research Scientist Senior Scientist cardiovascular molecular biology mouse model 2026",
    careersUrl: "https://www.biocon.com/careers" },
  { name: "Syngene International", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Syngene International Scientist Senior Scientist cardiovascular molecular biology in-vivo 2026" },
  { name: "AstraZeneca India", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "AstraZeneca India Research Scientist Senior Scientist cardiovascular molecular biology cardiac mouse 2026" },
  { name: "Dr Reddys Laboratories", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Dr Reddys Laboratories Scientist Senior Scientist molecular biology cardiovascular 2026" },
  { name: "Sun Pharma Research", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Sun Pharmaceutical Scientist Senior Scientist molecular biology cardiovascular 2026" },
  { name: "Novartis India", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Novartis India Research Scientist cardiovascular molecular biology Hyderabad 2026" },

  // ═══ INDIA — Tier 1 IITs (Biology / Biosciences) ═══
  { name: "IIT Bombay Biosciences", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Bombay assistant professor faculty biosciences biology cardiovascular molecular genetics 2026" },
  { name: "IIT Delhi Biochemical Engineering", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Delhi assistant professor faculty biochemistry molecular biology cardiovascular genetics 2026" },
  { name: "IIT Madras Biotechnology", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Madras assistant professor faculty biotechnology molecular biology cardiovascular 2026" },
  { name: "IIT Kanpur Biological Sciences", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Kanpur assistant professor faculty biology molecular genetics cardiovascular 2026" },
  { name: "IIT Kharagpur Biotechnology", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Kharagpur assistant professor faculty biotechnology molecular biology 2026" },

  // ═══ INDIA — IISERs (Tier 2 India Academics) ═══
  { name: "IISER Kolkata", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Kolkata faculty assistant professor cardiovascular molecular biology genetics 2026" },
  { name: "IISER Bhopal", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Bhopal faculty assistant professor biology molecular genetics cardiovascular 2026" },
  { name: "IISER Mohali", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Mohali faculty assistant professor molecular biology cardiovascular genetics 2026" },
  { name: "IISER Thiruvananthapuram", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Thiruvananthapuram faculty assistant professor molecular biology cardiovascular 2026" },

  // ═══ GLOBAL PHARMA — International sector ═══
  { name: "Roche", sector: "international", country: "Switzerland",
    apiType: "websearch", slowFetch: true,
    searchQuery: "Roche research scientist investigator cardiovascular genomics molecular biology 2026",
    careersUrl: "https://www.roche.com/careers" },
  { name: "GlaxoSmithKline GSK", sector: "industry", country: "UK",
    apiType: "websearch",
    searchQuery: "GSK GlaxoSmithKline research scientist cardiovascular molecular biology 2026",
    careersUrl: "https://www.gsk.com/en-gb/careers/" },

  // ═══ INTERNATIONAL — Additional Research Labs ═══
  { name: "WEHI Melbourne", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "WEHI Walter Eliza Hall Institute research scientist cardiovascular genomics 2026",
    careersUrl: "https://www.wehi.edu.au/careers" },
  { name: "MRC Harwell", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC Harwell Institute scientist researcher cardiovascular genomics molecular biology 2026" },

  // ═══ INTERNATIONAL — Top EU Academic Institutes ═══
  { name: "Heidelberg University Hospital", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Heidelberg University DKFZ postdoc cardiovascular molecular biology research scientist 2026" },
  { name: "Max Planck Institute for Molecular Biomedicine", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Max Planck Institute Molecular Biomedicine postdoc cardiovascular genomics 2026" },
  { name: "Hubrecht Institute", sector: "international", country: "Netherlands",
    apiType: "websearch",
    searchQuery: "Hubrecht Institute postdoc cardiovascular developmental biology genomics 2026" },
  { name: "University of Amsterdam AMC", sector: "international", country: "Netherlands",
    apiType: "websearch",
    searchQuery: "Amsterdam UMC postdoc cardiovascular molecular biology research scientist 2026" },
  { name: "Institut Pasteur Paris", sector: "international", country: "France",
    apiType: "websearch",
    searchQuery: "Institut Pasteur postdoc cardiovascular genomics molecular biology Paris 2026",
    careersUrl: "https://jobs.pasteur.fr" },
  { name: "Uppsala University", sector: "international", country: "Sweden",
    apiType: "websearch",
    searchQuery: "Uppsala University postdoc cardiovascular molecular biology genomics 2026" },
  { name: "University of Copenhagen BRIC", sector: "international", country: "Denmark",
    apiType: "websearch",
    searchQuery: "University Copenhagen BRIC postdoc cardiovascular molecular biology 2026" },
  { name: "Champalimaud Foundation", sector: "international", country: "Portugal",
    apiType: "websearch",
    searchQuery: "Champalimaud Foundation postdoc cardiovascular molecular biology genomics 2026" },

  // ═══ INTERNATIONAL — UK Depth (Cardiovascular strongholds) ═══
  { name: "University of Oxford Cardiovascular Medicine", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "University Oxford postdoc research scientist cardiovascular molecular biology Radcliffe BHF 2026",
    careersUrl: "https://www.jobs.ox.ac.uk" },
  { name: "University of Cambridge Heart and Lung", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "University Cambridge postdoc research scientist cardiovascular molecular biology MRC Wellcome 2026",
    careersUrl: "https://www.jobs.cam.ac.uk" },
  { name: "Imperial College London NHLI", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "Imperial College London NHLI postdoc research scientist cardiovascular molecular biology heart lung 2026",
    careersUrl: "https://www.imperial.ac.uk/jobs" },
  { name: "University College London Cardiovascular", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "UCL Institute Cardiovascular Science postdoc research scientist molecular biology genomics 2026",
    careersUrl: "https://www.ucl.ac.uk/work-at-ucl" },
  { name: "University of Edinburgh BHF Centre", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "University Edinburgh BHF Centre Cardiovascular Science postdoc research scientist molecular biology 2026",
    careersUrl: "https://www.vacancies.ed.ac.uk" },
  { name: "University of Manchester Cardiovascular", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "University Manchester postdoc research scientist cardiovascular molecular biology British Heart Foundation 2026" },
  { name: "British Heart Foundation Fellowships", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "British Heart Foundation BHF Intermediate Basic Science Fellowship cardiovascular molecular biology 2026 open call" },

  // ═══ INTERNATIONAL — Germany Depth ═══
  { name: "DZHK German Centre Cardiovascular Research", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "DZHK Deutsches Zentrum Herz-Kreislauf-Forschung postdoc scientist cardiovascular molecular biology 2026",
    careersUrl: "https://dzhk.de/en/careers" },
  { name: "Charité Berlin Cardiovascular", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Charité Berlin postdoc research scientist cardiovascular molecular biology genetics 2026",
    careersUrl: "https://career.charite.de" },
  { name: "University Heart Center Hamburg", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "University Heart Center Hamburg postdoc scientist cardiovascular molecular biology echocardiography 2026" },
  { name: "German Heart Center Munich", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "German Heart Center Munich Deutsches Herzzentrum postdoc scientist cardiovascular molecular biology 2026" },
  { name: "University Medical Center Göttingen", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "University Medical Center Göttingen UMG postdoc cardiovascular molecular medicine RNA-seq 2026" },

  // ═══ INTERNATIONAL — Netherlands Depth ═══
  { name: "Erasmus MC Rotterdam", sector: "international", country: "Netherlands",
    apiType: "websearch",
    searchQuery: "Erasmus MC Rotterdam postdoc research scientist cardiovascular molecular biology genomics 2026",
    careersUrl: "https://www.erasmusmc.nl/en/career" },

  // ═══ INTERNATIONAL — Belgium (world-class molecular biology) ═══
  { name: "KU Leuven Centre for Molecular Medicine", sector: "international", country: "Belgium",
    apiType: "websearch",
    searchQuery: "KU Leuven VIB postdoc research scientist cardiovascular molecular biology genomics 2026",
    careersUrl: "https://www.kuleuven.be/personeel/jobsite/en" },
  { name: "VIB Flanders Institute for Biotechnology", sector: "international", country: "Belgium",
    apiType: "websearch",
    searchQuery: "VIB Gent Leuven postdoc scientist cardiovascular molecular biology single-cell RNA-seq 2026",
    careersUrl: "https://www.vib.be/en/careers" },

  // ═══ INTERNATIONAL — Austria (top molecular medicine institutes) ═══
  { name: "IMP Vienna Research Institute", sector: "international", country: "Austria",
    apiType: "websearch",
    searchQuery: "IMP Vienna postdoc scientist molecular biology genetics cardiovascular RNA 2026",
    careersUrl: "https://www.imp.ac.at/career" },
  { name: "CeMM Vienna Molecular Medicine", sector: "international", country: "Austria",
    apiType: "websearch",
    searchQuery: "CeMM Vienna Research Center Molecular Medicine postdoc scientist cardiovascular genomics 2026",
    careersUrl: "https://cemm.at/careers" },

  // ═══ INTERNATIONAL — Finland ═══
  { name: "University of Helsinki Molecular Medicine", sector: "international", country: "Finland",
    apiType: "websearch",
    searchQuery: "University Helsinki postdoc research scientist cardiovascular molecular biology Finnish Cardiovascular Research 2026",
    careersUrl: "https://www.helsinki.fi/en/about-us/careers" },

  // ═══ INTERNATIONAL — Italy (genomics and molecular medicine) ═══
  { name: "San Raffaele Scientific Institute Milan", sector: "international", country: "Italy",
    apiType: "websearch",
    searchQuery: "IRCCS San Raffaele Milan postdoc scientist cardiovascular molecular biology genomics 2026",
    careersUrl: "https://www.hsr.it/en/careers" },

  // ═══ INTERNATIONAL — Spain ═══
  { name: "CNIO Madrid", sector: "international", country: "Spain",
    apiType: "websearch",
    searchQuery: "CNIO Spanish National Cancer Research Centre Madrid postdoc scientist molecular biology genomics cardiovascular 2026",
    careersUrl: "https://www.cnio.es/en/careers" },

  // ═══ INDUSTRY — European Pharma (cardiovascular-focused) ═══
  { name: "AstraZeneca UK Cambridge", sector: "industry", country: "UK",
    apiType: "websearch", slowFetch: true,
    searchQuery: "AstraZeneca Cambridge UK Scientist Senior Scientist cardiovascular heart failure molecular biology in-vivo mouse 2026",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "Bayer Research Germany", sector: "industry", country: "Germany",
    apiType: "websearch",
    searchQuery: "Bayer AG Research Scientist Senior Scientist cardiovascular molecular biology cardiac mouse model RNA-seq 2026",
    careersUrl: "https://www.bayer.com/en/worldwide/jobs" },
  { name: "Boehringer Ingelheim Germany", sector: "industry", country: "Germany",
    apiType: "websearch",
    searchQuery: "Boehringer Ingelheim Scientist Senior Scientist cardiovascular molecular biology heart failure mouse model 2026",
    careersUrl: "https://www.boehringer-ingelheim.com/careers" },
  { name: "Novo Nordisk Denmark", sector: "industry", country: "Denmark",
    apiType: "websearch",
    searchQuery: "Novo Nordisk Scientist Senior Scientist cardiovascular cardiometabolic molecular biology in-vivo 2026",
    careersUrl: "https://www.novonordisk.com/careers" },

  // ═══ INTERNATIONAL — Singapore & Australia ═══
  { name: "Duke-NUS Medical School", sector: "international", country: "Singapore",
    apiType: "websearch",
    searchQuery: "Duke-NUS Singapore postdoc cardiovascular molecular biology research scientist 2026",
    careersUrl: "https://www.duke-nus.edu.sg/careers" },
  { name: "NUS Yong Soo Lin School of Medicine", sector: "international", country: "Singapore",
    apiType: "websearch",
    searchQuery: "NUS National University Singapore postdoc cardiovascular molecular biology faculty 2026" },
  { name: "Baker Heart Institute", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "Baker Heart Diabetes Institute Melbourne postdoc cardiovascular research scientist 2026",
    careersUrl: "https://baker.edu.au/careers" },
  { name: "Victor Chang Cardiac Research Institute", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "Victor Chang Cardiac Research Institute postdoc cardiovascular molecular biology 2026" },

  // ═══ INTERNATIONAL — Canada ═══
  { name: "Montreal Clinical Research Institute", sector: "international", country: "Canada",
    apiType: "websearch",
    searchQuery: "IRCM Montreal postdoc cardiovascular molecular biology genomics 2026" },
  { name: "University of British Columbia", sector: "international", country: "Canada",
    apiType: "websearch",
    searchQuery: "UBC University British Columbia postdoc cardiovascular molecular biology faculty 2026" },

  // ═══ ACADEMIA — Additional US Tier 1 ═══
  { name: "Duke University Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Duke University postdoc cardiovascular molecular biology research scientist 2026" },
  { name: "University of Michigan Medical School", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "University Michigan postdoc cardiovascular molecular biology genomics 2026" },
  { name: "Vanderbilt University Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Vanderbilt University postdoc cardiovascular molecular biology 2026" },
  { name: "University of Pennsylvania Perelman", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UPenn Perelman School Medicine postdoc cardiovascular molecular biology 2026" },
  { name: "Northwestern University Feinberg", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Northwestern Feinberg postdoc cardiovascular molecular biology genomics 2026" },
]

// Total: ~100 Orgs — Tier 1-4 India Academics, Global Pharma, International Research Labs
// Last updated: 2026-03-20
