export interface MonitorOrg {
  name: string
  sector: 'academia' | 'industry' | 'international' | 'india'
  country: string
  careersUrl?: string
  rssUrl?: string
  apiType: 'rss' | 'usajobs' | 'websearch' | 'adzuna' | 'natureJobs'
  searchQuery: string
  slowFetch?: boolean  // Add extra inter-scan delay to respect org rate limits
}

// ─── webSearch is ONLY used for orgs with no free source ─────────────────────
// Max 15 websearch orgs. All others use RSS or USAJobs (free, no AI cost).
// Cost: ~60 webSearch calls/month @ ~$0.03/call = ~$1-2/month for monitor

export const MONITOR_ORGS: MonitorOrg[] = [
  // ═══ ACADEMIA — US Government (USAJobs — free, no AI cost) ═══
  { name: "NIH NHLBI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "cardiovascular postdoc researcher NHLBI" },
  { name: "NIH NIGMS", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "postdoctoral researcher molecular biology NIGMS" },
  { name: "NIH NCI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cancer biology NCI" },
  { name: "FDA", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist molecular biology FDA" },
  { name: "CDC", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cardiovascular molecular biology CDC" },

  // ═══ ACADEMIA — RSS feeds (free, no AI cost) ═══
  { name: "Cold Spring Harbor Laboratory", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://cshl.edu/careers/feed/",
    searchQuery: "Cold Spring Harbor postdoc molecular biology genomics" },
  { name: "Nature Jobs", sector: "academia", country: "Global",
    apiType: "rss",
    rssUrl: "https://www.nature.com/naturecareers/rss/latest",
    searchQuery: "postdoc cardiovascular molecular biology nature jobs" },
  { name: "Science Careers", sector: "academia", country: "Global",
    apiType: "rss",
    rssUrl: "https://jobs.sciencecareers.org/rss/jobs/",
    searchQuery: "postdoc cardiovascular molecular biology science careers" },
  { name: "Jobs.ac.uk", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.jobs.ac.uk/search/?rss=1&keywords=cardiovascular+postdoc+molecular+biology",
    searchQuery: "cardiovascular postdoc molecular biology UK" },
  { name: "EuroScienceJobs", sector: "international", country: "Europe",
    apiType: "rss",
    rssUrl: "https://www.eurosciencejobs.com/rss/jobs",
    searchQuery: "postdoc cardiovascular molecular biology Europe" },
  { name: "EMBL Jobs", sector: "international", country: "Germany",
    apiType: "rss",
    rssUrl: "https://www.embl.org/jobs/rss/",
    searchQuery: "EMBL postdoctoral fellowship cardiovascular molecular biology" },
  { name: "Wellcome Sanger Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.sanger.ac.uk/careers/rss/",
    searchQuery: "Wellcome Sanger postdoctoral researcher genomics cardiovascular" },
  { name: "Francis Crick Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.crick.ac.uk/careers/vacancies/rss",
    searchQuery: "Francis Crick postdoc cardiovascular molecular biology" },
  { name: "HigherEdJobs", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://www.higheredjobs.com/rss/jobFeed.cfm?JobCat=203",
    searchQuery: "postdoc cardiovascular molecular biology US university" },

  // ═══ ACADEMIA — webSearch (no free source — keep to 15 total) ═══
  { name: "Harvard Medical School", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Harvard Medical School postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://academicpositions.harvard.edu" },
  { name: "Stanford Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Stanford Medicine postdoctoral researcher cardiovascular 2026",
    careersUrl: "https://med.stanford.edu/careers" },
  { name: "Mayo Clinic Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Mayo Clinic postdoc research scientist cardiovascular 2026",
    careersUrl: "https://jobs.mayoclinic.org" },
  { name: "Broad Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Broad Institute postdoctoral associate genomics molecular biology 2026",
    careersUrl: "https://www.broadinstitute.org/careers" },
  { name: "MIT Biology", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "MIT postdoctoral researcher molecular biology cardiovascular 2026" },
  { name: "UCSF", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UCSF postdoc cardiovascular cell biology molecular biology 2026",
    careersUrl: "https://jobs.ucsf.edu" },
  { name: "Johns Hopkins Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Johns Hopkins postdoctoral researcher cardiovascular 2026",
    careersUrl: "https://jobs.jhu.edu" },
  { name: "Salk Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Salk Institute postdoc cardiovascular cell biology 2026",
    careersUrl: "https://www.salk.edu/careers" },
  { name: "Columbia University Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Columbia University postdoc cardiovascular research 2026" },
  { name: "Yale School of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Yale Medicine postdoctoral researcher cardiovascular 2026" },
  { name: "Gladstone Institutes", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Gladstone Institutes postdoc cardiovascular genomics 2026",
    careersUrl: "https://gladstone.org/careers" },
  { name: "Scripps Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Scripps Research postdoctoral scientist cardiovascular 2026" },
  { name: "UT Southwestern Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UT Southwestern postdoc cardiovascular research 2026" },
  { name: "Baylor College of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Baylor College Medicine postdoc cardiovascular 2026" },
  { name: "Washington University St Louis", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "WashU postdoctoral researcher cardiovascular molecular biology 2026" },
  { name: "Weill Cornell Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Weill Cornell postdoc cardiovascular research scientist 2026" },

  // ═══ INDUSTRY — webSearch (no free API for these orgs) ═══
  { name: "Genentech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Genentech research scientist cardiovascular molecular biology 2026",
    careersUrl: "https://www.gene.com/careers" },
  { name: "AstraZeneca US", sector: "industry", country: "USA",
    apiType: "websearch", slowFetch: true,
    searchQuery: "AstraZeneca research scientist cardiovascular postdoc 2026",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "Novartis US", sector: "industry", country: "USA",
    apiType: "websearch", slowFetch: true,
    searchQuery: "Novartis research scientist cardiovascular molecular biology 2026" },
  { name: "Pfizer Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Pfizer research scientist cardiovascular cell biology 2026" },
  { name: "Amgen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Amgen research scientist cardiovascular molecular biology 2026",
    careersUrl: "https://careers.amgen.com" },
  { name: "Bristol Myers Squibb", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "BMS research scientist cardiovascular genomics 2026" },
  { name: "Regeneron", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Regeneron scientist cardiovascular molecular biology 2026",
    careersUrl: "https://careers.regeneron.com" },
  { name: "Moderna", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Moderna research scientist molecular biology cardiovascular 2026" },
  { name: "Eli Lilly", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Eli Lilly research scientist cardiovascular 2026" },
  { name: "Merck Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Merck research scientist cardiovascular molecular biology 2026" },
  { name: "Biogen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Biogen research scientist cardiovascular cell biology 2026" },
  { name: "Vertex Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Vertex research scientist molecular biology genomics 2026" },
  { name: "Alnylam Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Alnylam scientist cardiovascular RNA therapeutics 2026" },
  { name: "10x Genomics", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "10x Genomics scientist spatial transcriptomics molecular biology 2026" },
  { name: "Illumina", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Illumina research scientist genomics molecular biology 2026" },
  { name: "Recursion Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Recursion scientist cell biology computational biology 2026" },
  { name: "BioNTech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "BioNTech research scientist molecular biology cardiovascular 2026" },
  { name: "Sanofi Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Sanofi research scientist cardiovascular molecular biology 2026" },
  { name: "Janssen Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Janssen research scientist cardiovascular cell biology 2026" },
  { name: "Pacific Biosciences", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "PacBio scientist molecular biology genomics sequencing 2026" },

  // ═══ INTERNATIONAL — RSS feeds (free, no AI cost) ═══
  { name: "MRC LMS London", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC London Institute Medical Sciences postdoc cardiovascular 2026" },
  { name: "Max Planck Heart and Lung", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Max Planck Institute Heart Lung postdoc cardiovascular 2026" },
  { name: "Karolinska Institute", sector: "international", country: "Sweden",
    apiType: "websearch",
    searchQuery: "Karolinska Institute postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://ki.se/en/vacancies" },
  { name: "ETH Zurich", sector: "international", country: "Switzerland",
    apiType: "websearch",
    searchQuery: "ETH Zurich postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://jobs.ethz.ch" },
  { name: "University of Toronto", sector: "international", country: "Canada",
    apiType: "websearch",
    searchQuery: "University of Toronto postdoc cardiovascular molecular biology 2026" },
  { name: "A*STAR Singapore", sector: "international", country: "Singapore",
    apiType: "websearch",
    searchQuery: "ASTAR Singapore postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://www.a-star.edu.sg/careers" },
  { name: "Peter MacCallum Cancer Centre", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "Peter MacCallum postdoc molecular biology genomics 2026" },

  // ═══ INDIA — webSearch (no free API available for Indian institutes) ═══
  { name: "NCBS Bangalore", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "NCBS Bangalore research scientist faculty cardiovascular molecular biology 2026",
    careersUrl: "https://www.ncbs.res.in/jobs" },
  { name: "TIFR Mumbai", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "TIFR Mumbai postdoc biology cardiovascular research position 2026" },
  { name: "IISc Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IISc Bangalore postdoc molecular biology cardiovascular 2026" },
  { name: "IGIB Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IGIB Delhi postdoc genomics molecular biology cardiovascular 2026" },
  { name: "CCMB Hyderabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "CCMB Hyderabad postdoc molecular biology cell biology 2026" },
  { name: "inStem Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "inStem Bangalore postdoc cardiovascular stem cell biology 2026" },
  { name: "NII Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "NII Delhi postdoc immunology molecular biology 2026" },
  { name: "JNCASR Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "JNCASR Bangalore postdoc molecular biology 2026" },
  { name: "IISER Pune", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Pune faculty scientist biology cardiovascular molecular 2026" },
  { name: "RCB Faridabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "RCB Faridabad postdoc molecular biology cardiovascular 2026" },
  { name: "DBT-THSTI Faridabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "THSTI Faridabad postdoc cardiovascular translational research 2026" },
  { name: "RGCB Trivandrum", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "RGCB Trivandrum postdoc molecular biology cardiovascular 2026" },
  { name: "Biocon Biologics", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Biocon research scientist molecular biology 2026",
    careersUrl: "https://www.biocon.com/careers" },
  { name: "Syngene International", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Syngene research scientist molecular biology cardiovascular 2026" },
  { name: "AstraZeneca India", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "AstraZeneca India research scientist cardiovascular molecular biology 2026" },

  // ═══ INDIA — Tier 1 IITs (Biology / Biosciences) ═══
  { name: "IIT Bombay Biosciences", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Bombay assistant professor faculty biosciences molecular biology cardiovascular 2026" },
  { name: "IIT Delhi Biochemical Engineering", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Delhi assistant professor faculty biochemistry molecular biology 2026" },

  // ═══ INDIA — IISERs (Tier 2 India Academics) ═══
  { name: "IISER Kolkata", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Kolkata faculty scientist assistant professor cardiovascular molecular biology 2026" },
  { name: "IISER Bhopal", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Bhopal faculty scientist assistant professor biology genomics 2026" },
  { name: "IISER Mohali", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Mohali faculty scientist assistant professor molecular biology 2026" },
  { name: "IISER Thiruvananthapuram", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Thiruvananthapuram faculty scientist molecular biology cardiovascular 2026" },

  // ═══ GLOBAL PHARMA — International sector ═══
  { name: "Roche", sector: "international", country: "Switzerland",
    apiType: "websearch", slowFetch: true,
    searchQuery: "Roche research scientist investigator cardiovascular genomics molecular biology 2026",
    careersUrl: "https://www.roche.com/careers" },
  { name: "GlaxoSmithKline GSK", sector: "industry", country: "UK",
    apiType: "websearch",
    searchQuery: "GSK GlaxoSmithKline research scientist cardiovascular molecular biology 2026",
    careersUrl: "https://www.gsk.com/en-gb/careers/" },

  // ═══ INTERNATIONAL — Additional Research Labs ═══
  { name: "WEHI Melbourne", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "WEHI Walter Eliza Hall Institute research scientist cardiovascular genomics 2026",
    careersUrl: "https://www.wehi.edu.au/careers" },
  { name: "MRC Harwell", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC Harwell Institute scientist researcher cardiovascular genomics molecular biology 2026" },
]

// Total: 82 Orgs — Tier 1-4 India Academics, Global Pharma, International Research Labs

// Deployment Trigger: 2026-03-18 17:35:42

// FORCE DEPLOY SYNC: 82 ORGS - 03/18/2026 17:42:31

// Final Sync Trigger: 03/18/2026 18:03:43
